sdkversion: "3.5.0"
name: "googlemap"
version: "1.0"
vendor: "rhomobile"
build: "debug"
bbver: "4.6"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator5.0"
  provisionprofile: 
  codesignidentity: 
  entitlements: 
  BundleIdentifier: "com.rhomobile.googlemap"
  BundleURLScheme: "googlemap"
wp:
  productid: "00f674a0-e6fa-0130-414a-6ca86b26d92c"
symbian:
  uid: "0xeacc8580"
android:
  version: "2.1"
  emulator: "RhoAndroid233"
extensions:
  - json
  - another-extension
app_type: "rhoelements"
capabilities:
  - non_motorola_device
